table inet BastionRules {
	chain input {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		ct state established,related accept
		tcp dport 22 ct state new accept
		ip protocol icmp accept
	}

	chain forward {
		type filter hook forward priority filter; policy drop;
		ct state established,related accept
		iif "enp0s9" oif "enp0s3" ct state established,related,new accept
		iif "enp0s3" oif "enp0s9" tcp dport 22 ct state established,related,new accept
	}

	chain output {
		type filter hook output priority filter; policy accept;
	}
}
table ip nat {
	chain postrouting {
		type nat hook postrouting priority srcnat; policy accept;
		oif "enp0s3" masquerade
		oif "enp0s3" masquerade
	}
}
